import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import {
  CollectionHeroGroup,
  PopularCollection,
} from '../components/organism/collection-hero-group'

type HomePageProps = {
  popularCollections: PopularCollection[]
}

export const getStaticProps: GetStaticProps = async () => {
  const popularCollections: PopularCollection[] = [
    {
      title: 'By type',
      projects: [
        {
          title: 'Back-end',
          desc: 'APIs, transformation etc.',
          url: 'collection/back-end',
        },
        {
          title: 'Web',
          desc: 'by this I mean websites',
          url: 'collection/web',
        },
        {
          title: 'Data',
          desc: 'Data scraping and all its fun',
          url: 'collection/web',
        },
      ],
    },
    {
      title: 'By difficulty',
      projects: [
        {
          title: 'Beginner',
          desc: '0-2 years experience',
          url: 'collection/back-end',
        },
        {
          title: 'Intermediate',
          desc: '2-5 years experience (roughly)',
          url: 'collection/web',
        },
        {
          title: 'Expert',
          desc: '6+ years (roughly)',
          url: 'collection/web',
        },
      ],
    },
    {
      title: 'By language',
      projects: [
        {
          title: 'Java',
          desc: 'The OG Object Oriented language',
          url: 'collection/back-end',
        },
        {
          title: 'Javascript (& Typescript)',
          desc: 'The modern langauge for the web.',
          url: 'collection/web',
        },
        {
          title: 'Python',
          desc: 'AI, Robots, Data - easily done in Python',
          url: 'collection/web',
        },
      ],
    },
  ]

  return {
    props: {
      popularCollections: popularCollections,
    },
  }
}

const Home: NextPage<HomePageProps> = (props: HomePageProps) => {
  const { popularCollections } = props
  return (
    <>
      <Head>
        <title>100 Projects</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>
      <main>
        <h1 className="text-primary-ctaText hover:text-primary-highlight hover:cursor-pointer">
          Popular Projects
        </h1>
        {popularCollections &&
          popularCollections.map((popularCollection) => (
            <CollectionHeroGroup
              key={popularCollection.title}
              collection={popularCollection || []}
            />
          ))}
        {!popularCollections && <h1>Loading</h1>}
      </main>
    </>
  )
}

export default Home
